r"""
workspace.py — first-launch bootstrap.

Called once at app start. Idempotent: safe to run every launch; it only creates
what's missing and never overwrites real data.

On a fresh machine it builds, under D:\\Sarthi - Plan My Day\\ (see paths.py):

  Sarthi - Plan My Day\\
    README.md                         <- md: what this folder is
    _common\\
      users_master.xlsx               <- xlsx: logins
      monthly_targets.xlsx            <- xlsx
      learning_bank.xlsx              <- xlsx
      role_prompts\\
        sales_rm.md, trainer.md, ...  <- md: the role coaching prompts
    <user_key>\\
      monthly_plan.xlsx               <- xlsx
      monthly_achievement.xlsx        <- xlsx
      tasks.xlsx                      <- xlsx
      day_updates.xlsx                <- xlsx
      briefs\\                         <- md daily briefs land here
      reports\\                        <- docx + xlsx reports land here

The Word/md daily artifacts themselves are generated by report.py as the app
runs; this module guarantees the folders and the seed/reference files exist.
"""

import os
import pandas as pd

import paths
import schemas
import storage

ROLE_PROMPT_TEMPLATE = """# Role Prompt: {title}

## Role Objective
{objective}

## Core KPIs
{kpis}

## Correct Daily Behaviours
- Track your numbers before planning anything else.
- Put direct-impact work first when a KPI is behind.
- Keep tasks small, with a clear expected output and success metric.

## Common Pitfalls
- Filling the day with activity that doesn't move a committed number.
- Planning follow-ups without defining what output they should produce.

## Pushback Rules
- If a KPI is Critical or Behind, challenge any plan that leads with indirect work.
- Never block a task — flag it as unlinked and let the person decide.

## Task Breakdown Rules
- Every task gets a measurable output and a success metric.
- Tag each task Today (delivers now) or Build (prepares tomorrow).
"""

ROLES = {
    "sales_rm": ("Sales RM",
                 "Grow revenue, trade activation, and new accounts from your book.",
                 "- Revenue\n- Trade Activation\n- New Accounts"),
    "trainer": ("Trainer",
                "Deliver trainings that change behaviour, and validate their impact.",
                "- Trainings Delivered\n- Impact Validation"),
    "b2b": ("B2B",
            "Drive partner-led account opening, activation, and partner productivity.",
            "- New Accounts\n- Active Partners\n- Trade Activation"),
    "lead": ("Lead",
             "Keep the team's daily actions laddering up to the monthly numbers.",
             "- Team Target Attainment\n- Coverage\n- Pushback Quality"),
    "member": ("Member",
               "Execute your committed plan and keep your numbers on track.",
               "- Your committed KPIs"),
    "partner_acquisition": ("Partner Acquisition Manager",
               "Acquire and grow partners across the full lifecycle — meet in person, "
               "onboard, drive lead generation and account opening, activate, cross-sell.",
               "- Partners Acquired\n- Partners Onboarded\n- Accounts Opened\n"
               "- Accounts Activated\n- Cross-sell Revenue\n- Follow-ups Worked"),
}

# Roles whose coaching prompt is hand-written (richer than the generic template).
PARTNER_ACQUISITION_PROMPT = """# System Prompt — Partner Acquisition Manager

## Who this role is
You are the AI coach for a **Partner Acquisition Manager** at a broking firm. This
person acquires partners by meeting them in person and then grows each partner across
the full lifecycle — from first handshake to ongoing, activated, cross-sold revenue.
They do not just sign partners; they own the partner's productivity. Strong follow-up
is the spine of everything they do: every partner touched is followed up hard, and
nothing is allowed to go cold.

Ground every judgement, task, and step in this role. The MIS numbers are meaningless
without it — this prompt tells you which KPIs matter, what "behind" implies, and what
a good day actually looks like for this person.

## The five-stage pipeline (run every day)
1. **Acquire** — meet new partners in person and sign them.
   The engine behind acquisition: **data -> call the data -> book a meeting -> meet ->
   pitch -> close -> capture as follow-up.** A plan that says "open N partners today" is
   hollow unless the follow-ups and booked meetings to reach N already exist.
2. **Onboard** — once signed, train and guide the partner: understand his business
   model, show him how to generate leads, give him ideas and cues. An un-onboarded
   partner never produces.
3. **Lead generation + Account opening** (treat as one) — drive the partner to
   generate leads daily, follow up, talk, support him, and convert leads into opened
   accounts. This is the daily engine of the business.
4. **Activation** — an opened account is worthless until it trades. Work with the
   partner to understand client profiles and get accounts activated. Activation is
   where opening turns into value; it is the most common place the number gets stuck.
5. **Cross-sell** — push the partner to cross-sell across his client base.

## Core KPIs
- Partners Acquired
- Partners Onboarded
- Accounts Opened (with lead generation)
- Accounts Activated
- Cross-sell Revenue
- Follow-ups Worked (cross-cutting)

## How to think before committing to a number (the first question back)
When the user commits to an outcome ("today I will open 10 partners / 300 accounts"),
do not just make tasks. First surface the pipeline reality:
- How many **HOT** follow-ups do they have? How many **COLD**? How much fresh **data**?
- If hot follow-ups exist -> contact them first; that is the warmest path to a close.
- If follow-ups are thin -> the real first task is **call the data and book meetings**.
- For account opening -> it runs **through partners**: which onboarded partners are
  generating leads, and whose clients are mid-KYC? Account opening is not a solo task.
Name the missing pipeline step rather than silently accepting the target.

## Follow-up discipline
- Every acquired or met partner becomes a tracked follow-up.
- Grade follow-ups hot / warm / cold; hot ones get same-day contact.
- A follow-up is "worked" only when it has a next action AND a date.
- After every meeting, capture the partner commitment as a follow-up immediately —
  an "I will get back to you" with no logged follow-up is a lost partner.

## Pre-meeting readiness (use when breaking a "meet partner" task into steps)
- Pitch ready and rehearsed.
- Content, brochures, and material in hand.
- Platform demo ready to show.
- Listing card ready to present.
- Show up sharp — well-groomed, properly dressed, presentable.

## Coaching / pushback rules
- Read the WHOLE pipeline, not one stage. If the plan is all acquisition meetings but
  accounts opened/activated are behind, say: "you are acquiring, but your number is
  stuck at activation — add an activation push."
- If a partner-meeting task has no readiness steps, prompt to break it down.
- If "open N partners/accounts" is planned with no data-calling or follow-up task
  behind it, point out the missing pipeline step.
- Never block a task. Flag the gap plainly, in one line, and let the person decide.
- Never flatter. Be warm but firm. Tie every point to a specific KPI and its stage.

## Task generation & breakdown rules
- Every task gets a concrete, countable expected output and a success metric.
- Tag each task Today (delivers now) or Build (prepares tomorrow pipeline).
- "Meet partner X" -> break into the pre-meeting readiness checklist + a capture-the-
  follow-up step.
- "Open N accounts" -> break into partner-driven steps (identify producing partners,
  push lead generation, move clients through KYC, confirm activation), not generic
  back-office account-opening steps.
"""

SPECIAL_PROMPTS = {"partner_acquisition": PARTNER_ACQUISITION_PROMPT}

README_TEXT = """# Sarthi - Plan My Day

This folder is created and maintained by the Plan My Day desktop app.
It holds everything the app needs, all on this machine — no cloud, no login server.

## What's here

- `_common\\` — shared files: logins, monthly targets, the learning bank, and the
  role-prompt coaching files (`role_prompts\\*.md`, safe to edit in any text editor).
- One folder per user (e.g. `vikrant\\`) holding that person's Excel data plus their
  generated daily briefs (`briefs\\*.md`) and reports (`reports\\*.docx`, `*.xlsx`).

## Safe to do

- Open the Excel files to read them. Close them before the app saves, or the app
  will wait for the lock.
- Edit the role-prompt `.md` files to tune how the AI coach behaves per role.

## Please don't

- Rename or move this folder while the app is configured to use it.
- Delete `_common\\users_master.xlsx` — it holds the logins.

The app re-creates anything missing on next launch, but it won't bring back data
you delete.
"""


def _ensure_excel(path, columns):
    """Create an empty xlsx with the right headers if it doesn't exist yet."""
    if not os.path.exists(path):
        storage._write(path, pd.DataFrame(columns=columns), columns)
        return True
    return False


def _ensure_text(path, text):
    if not os.path.exists(path):
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        return True
    return False


def ensure_workspace(seed_demo=True):
    """Create the full tree if missing. Returns a small report of what was made."""
    created = []

    # --- cloud (Google Sheets + Drive) bootstrap ---
    try:
        import gsheets
        if gsheets.enabled():
            return _bootstrap_cloud(seed_demo)
    except Exception as e:
        created.append(f"(cloud bootstrap error: {e})")

    # --- folders ---
    for d in (paths.base_dir(), paths.common_dir(), paths.role_prompts_dir()):
        if not os.path.isdir(d):
            os.makedirs(d, exist_ok=True)
            created.append(d)

    # --- README ---
    if _ensure_text(os.path.join(paths.base_dir(), "README.md"), README_TEXT):
        created.append("README.md")

    # --- role prompt md files ---
    _ensure_excel(os.path.join(paths.common_dir(), "team_roster.xlsx"), schemas.TEAM_ROSTER)
    # the master system prompt (companion's constitution) — editable on disk
    import ai as _ai
    if _ensure_text(os.path.join(paths.common_dir(), "system_prompt.md"), _ai.MASTER_FALLBACK):
        created.append("system_prompt.md")
    for role, (title, objective, kpis) in ROLES.items():
        p = os.path.join(paths.role_prompts_dir(), f"{role}.md")
        text = SPECIAL_PROMPTS.get(role) or ROLE_PROMPT_TEMPLATE.format(
            title=title, objective=objective, kpis=kpis)
        if _ensure_text(p, text):
            created.append(f"role_prompts/{role}.md")

    # --- common excel files ---
    if _ensure_excel(os.path.join(paths.common_dir(), "users_master.xlsx"), schemas.USERS):
        created.append("_common/users_master.xlsx")
    if _ensure_excel(os.path.join(paths.common_dir(), "monthly_targets.xlsx"), schemas.MONTHLY_TARGETS):
        created.append("_common/monthly_targets.xlsx")
    learning_cols = getattr(schemas, "LEARNING_BANK",
                            ["learning_id", "date", "created_by_key", "role",
                             "learning_title", "what_worked", "what_did_not_work",
                             "evidence_type", "confidence_score", "status",
                             "created_at", "updated_at"])
    if _ensure_excel(os.path.join(paths.common_dir(), "learning_bank.xlsx"), learning_cols):
        created.append("_common/learning_bank.xlsx")

    # --- seed demo users/targets/plan on a truly fresh workspace ---
    if seed_demo and storage.get_users().empty:
        try:
            import seed
            seed.seed()  # writes users, targets, plan via storage (now atomic)
            created.append("seeded demo users + targets + plan")
        except Exception as e:
            created.append(f"(seed skipped: {e})")

    # --- per-user folders + excel + briefs/reports dirs ---
    for _, u in storage.get_users().iterrows():
        uk = u["user_key"]
        for d in (paths.user_dir(uk), paths.user_briefs_dir(uk), paths.user_reports_dir(uk)):
            os.makedirs(d, exist_ok=True)
        _ensure_excel(os.path.join(paths.user_dir(uk), "monthly_plan.xlsx"), schemas.MONTHLY_PLAN)
        _ensure_excel(os.path.join(paths.user_dir(uk), "monthly_achievement.xlsx"),
                      getattr(schemas, "MONTHLY_ACHIEVEMENT",
                              ["date", "month", "user_key", "kpi_name", "achievement_value",
                               "achievement_source", "remarks", "created_at"]))
        _ensure_excel(os.path.join(paths.user_dir(uk), "tasks.xlsx"), schemas.TASKS)
        _ensure_excel(os.path.join(paths.user_dir(uk), "day_goals.xlsx"), schemas.DAY_GOALS)
        _ensure_excel(os.path.join(paths.user_dir(uk), "meetings.xlsx"), schemas.MEETINGS)
        _ensure_excel(os.path.join(paths.user_dir(uk), "partners.xlsx"), schemas.PARTNERS)
        _ensure_excel(os.path.join(paths.user_dir(uk), "msg_schedules.xlsx"), schemas.MSG_SCHEDULES)
        _ensure_excel(os.path.join(paths.user_dir(uk), "msg_outbox.xlsx"), schemas.MSG_OUTBOX)
        _ensure_excel(os.path.join(paths.user_dir(uk), "monthly_progress.xlsx"), schemas.MONTHLY_PROGRESS)
        _ensure_excel(os.path.join(paths.user_dir(uk), "outcomes.xlsx"), schemas.OUTCOMES)
        _ensure_excel(os.path.join(paths.user_dir(uk), "coach_rules.xlsx"), schemas.COACH_RULES)
        _ensure_excel(os.path.join(paths.user_dir(uk), "day_updates.xlsx"), schemas.DAY_UPDATES)

    return {"base_dir": paths.base_dir(), "created": created}


if __name__ == "__main__":
    rep = ensure_workspace()
    print("Workspace:", rep["base_dir"])
    for c in rep["created"]:
        print("  +", c)
    if not rep["created"]:
        print("  (already complete — nothing to create)")


def _bootstrap_cloud(seed_demo=True):
    """First-run setup for the hosted app. To keep launches fast, this does ONE read to
    decide: if users already exist, the workspace is set up — return immediately. Only a
    truly empty backend does the (slower) prompt-writing + seeding."""
    import gsheets
    import ai as _ai

    if not storage.get_users().empty:
        return []   # already set up — no extra Google calls on launch

    created = []
    # prompts (first time only)
    gsheets.write_text("system_prompt.md", _ai.MASTER_FALLBACK)
    created.append("system_prompt.md")
    for role, (title, objective, kpis) in ROLES.items():
        text = SPECIAL_PROMPTS.get(role) or ROLE_PROMPT_TEMPLATE.format(
            title=title, objective=objective, kpis=", ".join(kpis))
        gsheets.write_text(f"{role}.md", text)
        created.append(f"{role}.md")
    # seed demo users/targets/plan
    if seed_demo:
        try:
            import seed
            seed.seed()
            created.append("seeded demo users + targets + plan")
        except Exception as e:
            created.append(f"(seed skipped: {e})")
    return created
